markdown:         rdiscount
pygments:         true
paginate:         4

title:            yongjianqin的博客
url:              http://yongjianqin.github.io/
feed:             /atom.xml
author:
    name:         yongjianqin
    email:        373957912@qq.com

follow:
    email:        373957912@qq.com
    github:       https://github.com/yongjianqin
description:      Just another blog theme -- the One

indexContent:     true


style:            /css/style.css
blogName:         yongjianqin
blogDesc:         yongjianqin的博客 
favicon:          /favicon.ico
theme:            default

disqus:           piznblog

copyright:        Copyright © 2011-2012 PIZn All rights reserved.
test:             ok
